Dataset derivation

1. Uses Nemotron Personas for personalities
2. Uses 2021 M&P Survey as the baseline for the splits

Step 1: Import dataset from Nemotron

In [1]:
import pandas as pd
import numpy as np

from datasets import load_dataset

ds = load_dataset("nvidia/Nemotron-Personas-Singapore")

print(ds)
print(ds.keys())
print(ds.num_rows)
print(ds.column_names)

c:\Users\chong\OneDrive - Singapore Management University\research\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

DatasetDict({
    train: Dataset({
        features: ['uuid', 'professional_persona', 'sports_persona', 'arts_persona', 'travel_persona', 'culinary_persona', 'persona', 'cultural_background', 'skills_and_expertise', 'skills_and_expertise_list', 'hobbies_and_interests', 'hobbies_and_interests_list', 'career_goals_and_ambitions', 'sex', 'age', 'marital_status', 'education_level', 'occupation', 'industry', 'planning_area', 'country'],
        num_rows: 148000
    })
})
dict_keys(['train'])
{'train': 148000}
{'train': ['uuid', 'professional_persona', 'sports_persona', 'arts_persona', 'travel_persona', 'culinary_persona', 'persona', 'cultural_background', 'skills_and_expertise', 'skills_and_expertise_list', 'hobbies_and_interests', 'hobbies_and_interests_list', 'career_goals_and_ambitions', 'sex', 'age', 'marital_status', 'education_level', 'occupation', 'industry', 'planning_area', 'country']}

In [2]:
data = ds["train"]
df = data.to_pandas()

df.head()

,uuid,professional_persona,sports_persona,arts_persona,travel_persona,culinary_persona,persona,cultural_background,skills_and_expertise,skills_and_expertise_list,...,hobbies_and_interests_list,career_goals_and_ambitions,sex,age,marital_status,education_level,occupation,industry,planning_area,country
0,d792702ec018494e8e49c69120759408,"Yi Peng Yong, known as Danelle, a 20‑year‑old ...","Yi Peng Yong, known as Danelle, enjoys playing...","Yi Peng Yong, known as Danelle, spends her eve...","Yi Peng Yong, known as Danelle, meticulously p...","Yi Peng Yong, known as Danelle, delights in co...","Yi Peng Yong, known as Danelle, blends a love ...",Yi Peng Yong grew up in the multicultural neig...,She has developed solid expertise in wholesale...,"['Inventory management', 'Supply chain coordin...",...,['Reading personal development and business bo...,She aims to deepen her knowledge of retail ope...,Female,20,Single,Polytechnic,Senior Official or Manager,Wholesale & Retail Trade,Sengkang,Singapore
1,2fe149f1c59e47daa5e6ae0881ffef93,"Charmaine, a 53‑year‑old experienced clerical ...","Charmaine, a devoted fan of Brunei DPMM FC, fo...","Charmaine, an avid admirer of Jack Neo’s comed...","Charmaine, who dreams of a serene Japan onsen ...","Charmaine, a passionate home cook, delights in...","Charmaine, a sociable 53‑year‑old office whiz ...",Charmaine grew up in a bilingual Chinese house...,Charmaine is an experienced clerical worker wi...,"['Data entry', 'Inventory management', 'Custom...",...,"['Karaoke', 'Cooking Cantonese cuisine', 'Gard...",Charmaine aims to advance to a senior administ...,Female,53,Married,Secondary,Clerical Worker,Wholesale & Retail Trade,Choa Chu Kang,Singapore
2,dd95514790e84ffa9973475cfc706660,"Betty, a 29‑year‑old policy analyst in the Min...",Betty is an avid follower of Red Bull Racing’s...,Betty’s artistic palate is shaped by her love ...,Betty meticulously plans her cherry‑blossom pi...,Betty excels at preparing classic Chinese dish...,Betty is a methodical policy pro who balances ...,Wei Qi Leong grew up in a middle‑class Chinese...,Betty has developed strong analytical and orga...,"['Policy analysis', 'Program management', 'Dat...",...,"['Reading non-fiction', 'Chinese calligraphy',...",Betty aims to advance to a senior policy advis...,Female,29,Single,University,Professional,Public Administration & Education Services,Clementi,Singapore
3,a2d66162e29f420aa93c670a41eb4fd2,"Jian Choy Ker, a retired hawker stall propriet...","Jian Choy Ker, though in his nineties, stays c...",Jian Choy Ker immerses himself in classic Cant...,Jian Choy Ker prefers relaxed staycations with...,"Jian Choy Ker, a seasoned hawker‑style cook, d...","Jian Choy Ker, a 91‑year‑old former hawker who...",Jian Choy Ker grew up in a traditional Chinese...,Through decades of work as a hawker stall prop...,"['Mandarin and Cantonese fluency', 'Basic Engl...",...,"['Mahjong', 'Chinese calligraphy', 'Gardening'...","Although retired, Jian aims to maintain good h...",Male,91,Married,Primary,Retired,NaN,Sengkang,Singapore
4,98a3e5752be446ebaca994b8a390b290,"Aixin Noy Yong, a dedicated homemaker turned c...","Aixin Noy Yong, a quiet admirer of the Golden ...","Aixin Noy Yong, an ardent fan of Andy Lau, spe...",Aixin Noy Yong dreams of a serene Japanese ons...,"Aixin Noy Yong, a master of traditional cookin...","Aixin Noy Yong, a 68‑year‑old tea‑tin collecto...",Aixin grew up in a traditional Chinese Singapo...,"Aixin is adept at traditional Chinese cooking,...","['Chinese culinary arts (dim sum, herbal soups...",...,"['Reading Buddhist texts', 'Listening to class...","Although she identifies as a homemaker, Aixin ...",Female,68,Single,Other Diploma,Homemaker,NaN,Kallang,Singapore

Step 2:
Extract our direct fields from dataset that agents need.

In [3]:
cols = [
    "age",
    "sex",
    "marital_status",
    "education_level",
    "occupation",
    "industry",
    "planning_area",
    "persona",
    "cultural_background",
    "career_goals_and_ambitions"
]

df = df[cols].copy()
df.head()

,age,sex,marital_status,education_level,occupation,industry,planning_area,persona,cultural_background,career_goals_and_ambitions
0,20,Female,Single,Polytechnic,Senior Official or Manager,Wholesale & Retail Trade,Sengkang,"Yi Peng Yong, known as Danelle, blends a love ...",Yi Peng Yong grew up in the multicultural neig...,She aims to deepen her knowledge of retail ope...
1,53,Female,Married,Secondary,Clerical Worker,Wholesale & Retail Trade,Choa Chu Kang,"Charmaine, a sociable 53‑year‑old office whiz ...",Charmaine grew up in a bilingual Chinese house...,Charmaine aims to advance to a senior administ...
2,29,Female,Single,University,Professional,Public Administration & Education Services,Clementi,Betty is a methodical policy pro who balances ...,Wei Qi Leong grew up in a middle‑class Chinese...,Betty aims to advance to a senior policy advis...
3,91,Male,Married,Primary,Retired,NaN,Sengkang,"Jian Choy Ker, a 91‑year‑old former hawker who...",Jian Choy Ker grew up in a traditional Chinese...,"Although retired, Jian aims to maintain good h..."
4,68,Female,Single,Other Diploma,Homemaker,NaN,Kallang,"Aixin Noy Yong, a 68‑year‑old tea‑tin collecto...",Aixin grew up in a traditional Chinese Singapo...,"Although she identifies as a homemaker, Aixin ..."

Step 3: Filter out age
Step 4: create age buckets for filtering

In [4]:
df = df[(df["age"] >= 21) & (df["age"] <= 45)].copy()
df.head()

def age_bucket(age):
    if 21 <= age <= 25:
        return "21-25"
    elif 26 <= age <= 30:
        return "26-30"
    elif 31 <= age <= 35:
        return "31-35"
    elif 36 <= age <= 40:
        return "36-40"
    elif 41 <= age <= 45:
        return "41-45"
    else:
        return np.nan

df["age_bucket"] = df["age"].apply(age_bucket)
df.head()

,age,sex,marital_status,education_level,occupation,industry,planning_area,persona,cultural_background,career_goals_and_ambitions,age_bucket
2,29,Female,Single,University,Professional,Public Administration & Education Services,Clementi,Betty is a methodical policy pro who balances ...,Wei Qi Leong grew up in a middle‑class Chinese...,Betty aims to advance to a senior policy advis...,26-30
5,39,Male,Married,University,Senior Official or Manager,Manufacturing,Sengkang,"Qijie Huat Chua, a night-owl puzzle enthusiast...",Qijie Huat Chua grew up in a Singaporean Chine...,He aims to advance to a C‑suite role such as C...,36-40
6,42,Female,Married,Post Secondary (Non-Tertiary),Homemaker,NaN,Jurong West,Wai Ting Soon is a habit‑driven planner who ca...,Wai Ting grew up in a traditional Chinese Sing...,While she values her role as a full‑time homem...,41-45
7,42,Male,Single,University,Professional,Financial & Insurance Services,Queenstown,Chongyong Ang balances a spreadsheet‑obsessed ...,Chongyong grew up in a typical Chinese Singapo...,Chongyong aims to progress to a senior managem...,41-45
9,31,Male,Single,University,Senior Official or Manager,Wholesale & Retail Trade,Woodlands,Yao Dar Teo (Daniel) is a data‑savvy retail st...,"Daniel grew up in Woodlands, a residential tow...",Daniel aims to advance to a senior director or...,31-35

Step 4: Standardise Education

In [13]:
def clean_education(x):
    x = str(x).lower()

    if any(k in x for k in ["secondary", "primary", "below", "ite", "n level", "o level"]):
        return "Secondary and below"

    elif any(k in x for k in ["diploma", "a level", "polytechnic", "junior college"]):
        return "Diploma / A-Level"

    elif any(k in x for k in ["degree", "bachelor", "master", "phd", "postgraduate", "university"]):
        return "Degree and above"

    else:
        return np.nan

df["education_bucket"] = df["education_level"].apply(clean_education)
df = df.dropna(subset=["education_bucket"])
df.head()

,age,sex,marital_status,education_level,occupation,industry,planning_area,persona,cultural_background,career_goals_and_ambitions,age_bucket,education_bucket,relationship_status_final
2,29,Female,Single,University,Professional,Public Administration & Education Services,Clementi,Betty is a methodical policy pro who balances ...,Wei Qi Leong grew up in a middle‑class Chinese...,Betty aims to advance to a senior policy advis...,26-30,Degree and above,Dating
5,39,Male,Married,University,Senior Official or Manager,Manufacturing,Sengkang,"Qijie Huat Chua, a night-owl puzzle enthusiast...",Qijie Huat Chua grew up in a Singaporean Chine...,He aims to advance to a C‑suite role such as C...,36-40,Degree and above,Married
6,42,Female,Married,Post Secondary (Non-Tertiary),Homemaker,NaN,Jurong West,Wai Ting Soon is a habit‑driven planner who ca...,Wai Ting grew up in a traditional Chinese Sing...,While she values her role as a full‑time homem...,41-45,Secondary and below,Married
7,42,Male,Single,University,Professional,Financial & Insurance Services,Queenstown,Chongyong Ang balances a spreadsheet‑obsessed ...,Chongyong grew up in a typical Chinese Singapo...,Chongyong aims to progress to a senior managem...,41-45,Degree and above,Single
9,31,Male,Single,University,Senior Official or Manager,Wholesale & Retail Trade,Woodlands,Yao Dar Teo (Daniel) is a data‑savvy retail st...,"Daniel grew up in Woodlands, a residential tow...",Daniel aims to advance to a senior director or...,31-35,Degree and above,Single

In [ ]:
import numpy as np

np.random.seed(42)

# copy existing relationship_status into a new column first
df["relationship_status_final"] = df["marital_status"]

# get indexes of rows currently labelled Single
single_idx = df[df["marital_status"] == "Single"].index

# shuffle the single indexes
single_idx = np.random.permutation(single_idx)

# split into half
half = len(single_idx) // 2

dating_idx = single_idx[:half]
remaining_single_idx = single_idx[half:]

# assign dating to half of the original single rows
df.loc[dating_idx, "relationship_status_final"] = "Dating"
df.loc[remaining_single_idx, "relationship_status_final"] = "Single"

# check result
df["relationship_status_final"].value_counts()

# remove widowed/divorced/ separated rows
df = df[df["relationship_status_final"].isin(["Single", "Dating", "Married"])]
df.head()

,age,sex,marital_status,education_level,occupation,industry,planning_area,persona,cultural_background,career_goals_and_ambitions,age_bucket,education_bucket,relationship_status_final
2,29,Female,Single,University,Professional,Public Administration & Education Services,Clementi,Betty is a methodical policy pro who balances ...,Wei Qi Leong grew up in a middle‑class Chinese...,Betty aims to advance to a senior policy advis...,26-30,Degree and above,Dating
5,39,Male,Married,University,Senior Official or Manager,Manufacturing,Sengkang,"Qijie Huat Chua, a night-owl puzzle enthusiast...",Qijie Huat Chua grew up in a Singaporean Chine...,He aims to advance to a C‑suite role such as C...,36-40,Degree and above,Married
6,42,Female,Married,Post Secondary (Non-Tertiary),Homemaker,NaN,Jurong West,Wai Ting Soon is a habit‑driven planner who ca...,Wai Ting grew up in a traditional Chinese Sing...,While she values her role as a full‑time homem...,41-45,Secondary and below,Married
7,42,Male,Single,University,Professional,Financial & Insurance Services,Queenstown,Chongyong Ang balances a spreadsheet‑obsessed ...,Chongyong grew up in a typical Chinese Singapo...,Chongyong aims to progress to a senior managem...,41-45,Degree and above,Single
9,31,Male,Single,University,Senior Official or Manager,Wholesale & Retail Trade,Woodlands,Yao Dar Teo (Daniel) is a data‑savvy retail st...,"Daniel grew up in Woodlands, a residential tow...",Daniel aims to advance to a senior director or...,31-35,Degree and above,Single

Sampling using M&P targets

In [ ]:
target = {
    "Single": {
        "n": 49,
        "age_bucket": {
            "21-25": 0.30,
            "26-30": 0.34,
            "31-35": 0.18,
            "36-40": 0.10,
            "41-45": 0.09,
        },
        "sex": {
            "Male": 0.52,
            "Female": 0.48,
        },
        "education_bucket": {
            "Secondary and below": 0.12,
            "Diploma / A-Level": 0.34,
            "Degree and above": 0.55,
        },
    },
    "Married": {
        "n": 51,
        "age_bucket": {
            "21-25": 0.01,
            "26-30": 0.09,
            "31-35": 0.24,
            "36-40": 0.30,
            "41-45": 0.37,
        },
        "sex": {
            "Male": 0.45,
            "Female": 0.55,
        },
        "education_bucket": {
            "Secondary and below": 0.16,
            "Diploma / A-Level": 0.28,
            "Degree and above": 0.56,
        },
    }
}

In [ ]:
def add_sampling_weights(group_df, group_name):
    group_df = group_df.copy()
    spec = target[group_name]

    group_df["weight"] = 1.0

    for col in ["age_bucket", "sex", "education_bucket"]:
        observed = group_df[col].value_counts(normalize=True).to_dict()
        target_dist = spec[col]

        def factor(value):
            obs = observed.get(value, 0)
            tgt = target_dist.get(value, 0)

            if obs == 0:
                return 0
            return tgt / obs

        group_df["weight"] *= group_df[col].apply(factor)

    return group_df

In [12]:
samples = []


group_df = df[df["relationship_status_final"] == group_name].copy()
group_df = add_sampling_weights(group_df, group_name)

n = target[group_name]["n"]

sampled = group_df.sample(
    n=n,
    weights="weight",
    replace=False,
    random_state=42
)

samples.append(sampled)

agents = pd.concat(samples).sample(frac=1, random_state=42).reset_index(drop=True)
agents["agent_id"] = [f"A{i+1:03d}" for i in range(len(agents))]

KeyError: 'gender'